services:
  mysql:
    image: mysql:8.0
    container_name: ginadmin-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Wayne123456
      MYSQL_DATABASE: han_ginadmin
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - ginadmin-network

  server:
    image: ginadmin-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ginadmin-server
    restart: always
    depends_on:
      - mysql
    ports:
      - "127.0.0.1:8040:8040" # 宿主机 gocron 要能访问 8040，绑定 127.0.0.1 保证不对外暴露
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./server/data:/go/src/ginadmin/data
    networks:
      - ginadmin-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: ginadmin-web
    restart: always
    depends_on:
      - server
    ports:
      - "80:80"
    networks:
      - ginadmin-network

  gocron:
    image: ouqg/gocron:latest
    container_name: ginadmin-gocron
    restart: always
    depends_on:
      - mysql
    ports:
      - "5920:5920"
    volumes:
      - /opt/gocron/conf:/app/conf
    networks:
      - ginadmin-network

volumes:
  mysql-data:

networks:
  ginadmin-network:
    driver: bridge
