// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wirex

import (
	"context"
	"monitor-gin-admin/internal/mods"
	"monitor-gin-admin/internal/mods/business"
	api2 "monitor-gin-admin/internal/mods/business/api"
	biz2 "monitor-gin-admin/internal/mods/business/biz"
	dal2 "monitor-gin-admin/internal/mods/business/dal"
	"monitor-gin-admin/internal/mods/rbac"
	"monitor-gin-admin/internal/mods/rbac/api"
	"monitor-gin-admin/internal/mods/rbac/biz"
	"monitor-gin-admin/internal/mods/rbac/dal"
	"monitor-gin-admin/pkg/util"
)

// Injectors from wire.go:

func BuildInjector(ctx context.Context) (*Injector, func(), error) {
	db, cleanup, err := InitDB(ctx)
	if err != nil {
		return nil, nil, err
	}
	cacher, cleanup2, err := InitCacher(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	auther, cleanup3, err := InitAuth(ctx)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	trans := &util.Trans{
		DB: db,
	}
	menu := &dal.Menu{
		DB: db,
	}
	menuResource := &dal.MenuResource{
		DB: db,
	}
	roleMenu := &dal.RoleMenu{
		DB: db,
	}
	bizMenu := &biz.Menu{
		Cache:           cacher,
		Trans:           trans,
		MenuDAL:         menu,
		MenuResourceDAL: menuResource,
		RoleMenuDAL:     roleMenu,
	}
	apiMenu := &api.Menu{
		MenuBIZ: bizMenu,
	}
	role := &dal.Role{
		DB: db,
	}
	userRole := &dal.UserRole{
		DB: db,
	}
	bizRole := &biz.Role{
		Cache:       cacher,
		Trans:       trans,
		RoleDAL:     role,
		RoleMenuDAL: roleMenu,
		UserRoleDAL: userRole,
	}
	apiRole := &api.Role{
		RoleBIZ: bizRole,
	}
	user := &dal.User{
		DB: db,
	}
	bizUser := &biz.User{
		Cache:       cacher,
		Trans:       trans,
		UserDAL:     user,
		UserRoleDAL: userRole,
	}
	apiUser := &api.User{
		UserBIZ: bizUser,
	}
	login := &biz.Login{
		Cache:       cacher,
		Auth:        auther,
		UserDAL:     user,
		UserRoleDAL: userRole,
		MenuDAL:     menu,
		UserBIZ:     bizUser,
	}
	apiLogin := &api.Login{
		LoginBIZ: login,
	}
	logger := &dal.Logger{
		DB: db,
	}
	bizLogger := &biz.Logger{
		LoggerDAL: logger,
	}
	apiLogger := &api.Logger{
		LoggerBIZ: bizLogger,
	}
	casbinx := &rbac.Casbinx{
		Cache:           cacher,
		MenuDAL:         menu,
		MenuResourceDAL: menuResource,
		RoleDAL:         role,
	}
	rbacRBAC := &rbac.RBAC{
		DB:        db,
		MenuAPI:   apiMenu,
		RoleAPI:   apiRole,
		UserAPI:   apiUser,
		LoginAPI:  apiLogin,
		LoggerAPI: apiLogger,
		Casbinx:   casbinx,
	}
	// === Business DAL instances ===
	hostRule := &dal2.HostRule{
		DB: db,
	}
	deleteUnauditedMaterial := &dal2.DeleteUnauditedMaterial{
		DB: db,
	}
	agentToken := &dal2.AgentToken{
		DB: db,
	}
	accountInfo := &dal2.AccountInfo{
		DB: db,
	}
	hostField := &dal2.HostField{
		DB: db,
	}
	hostAccount := &dal2.HostAccount{
		DB: db,
	}
	promotionMaterial := &dal2.PromotionMaterial{
		DB: db,
	}
	materialVideo := &dal2.MaterialVideo{
		DB: db,
	}

	// === Shared Oceanengine instance with AgentTokenDAL ===
	bizOceanengine := &biz2.Oceanengine{
		AgentTokenDAL: agentToken,
	}

	// === Business BIZ instances ===
	bizHostRule := &biz2.HostRule{
		HostRuleDAL:          hostRule,
		PromotionMaterialDAL: promotionMaterial,
	}
	bizHostField := &biz2.HostField{
		HostFieldDAL: hostField,
	}
	bizAccountInfo := &biz2.AccountInfo{
		AccountInfoDAL: accountInfo,
	}
	bizAgentToken := &biz2.AgentToken{
		AgentTokenDAL: agentToken,
	}
	bizHostAccount := &biz2.HostAccount{
		HostAccountDAL: hostAccount,
	}
	bizCrontab := &biz2.Crontab{
		AccountInfo:       accountInfo,
		Oceanengine:       bizOceanengine,
		AgentToken:        agentToken,
		HostRule:          hostRule,
		HostAccount:       hostAccount,
		PromotionMaterial: promotionMaterial,
		MaterialVideo:     materialVideo,
	}
	bizDeleteUnauditedMaterial := &biz2.DeleteUnauditedMaterial{
		DeleteUnauditedMaterialDAL: deleteUnauditedMaterial,
		Oceanengine:                bizOceanengine,
		PromotionMaterialDAL:       promotionMaterial,
	}

	// === API instances ===
	apiHostRule := &api2.HostRule{
		HostRuleBIZ:    bizHostRule,
		OceanengineBIZ: bizOceanengine,
	}
	apiHostField := &api2.HostField{
		HostFieldBIZ: bizHostField,
	}
	apiAccountInfo := &api2.AccountInfo{
		AccountInfoBIZ: bizAccountInfo,
	}
	apiAgentToken := &api2.AgentToken{
		AgentTokenBIZ: bizAgentToken,
	}
	apiHostAccount := &api2.HostAccount{
		HostAccountBIZ: bizHostAccount,
	}
	apiCrontab := &api2.Crontab{
		CrontabBIZ: bizCrontab,
	}
	apiDeleteUnauditedMaterial := &api2.DeleteUnauditedMaterial{
		DeleteUnauditedMaterialBIZ: bizDeleteUnauditedMaterial,
	}
	businessBusiness := &business.Business{
		DB:                         db,
		HostRuleAPI:                apiHostRule,
		HostFieldAPI:               apiHostField,
		HostAccountAPI:             apiHostAccount,
		AccountInfoAPI:             apiAccountInfo,
		AgentTokenAPI:              apiAgentToken,
		DeleteUnauditedMaterialAPI: apiDeleteUnauditedMaterial,
		CrontabAPI:                 apiCrontab,
	}
	modsMods := &mods.Mods{
		RBAC:     rbacRBAC,
		Business: businessBusiness,
	}
	injector := &Injector{
		DB:    db,
		Cache: cacher,
		Auth:  auther,
		M:     modsMods,
	}
	return injector, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
