[Middleware]

[Middleware.Recovery]
Skip = 3

[Middleware.CORS]
Enable = false
AllowOrigins = ["*"]
AllowMethods = ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"]
AllowHeaders = ["*"]
MaxAge = 86400
AllowWildcard = true
AllowWebSockets = true
AllowFiles = true

[Middleware.Trace]
RequestHeaderKey = "X-Request-Id"
ResponseTraceKey = "X-Trace-Id"

[Middleware.Logger]
MaxOutputRequestBodyLen = 4096
MaxOutputResponseBodyLen = 4096

[Middleware.CopyBody]
MaxContentLen = 134217728

[Middleware.Auth]
Disable = false
SkippedPathPrefixes = ["/api/v1/captcha/", "/api/v1/login", "/api/v1/crontab"]
SigningMethod = "HS512"
SigningKey = "XnEsT0S@"
OldSigningKey = ""
Expired = 86400

[Middleware.Auth.Store]
Type = "badger"
Delimiter = ":"

[Middleware.Auth.Store.Memory]
CleanupInterval = 60

[Middleware.Auth.Store.Badger]
Path = "data/auth"

[Middleware.Auth.Store.Redis]
Addr = ""
Username = ""
Password = ""
DB = 2

[Middleware.RateLimiter]
Enable = false
Period = 10
MaxRequestsPerIP = 1000
MaxRequestsPerUser = 500

[Middleware.RateLimiter.Store]
Type = "memory"

[Middleware.RateLimiter.Store.Memory]
Expiration = 3600
CleanupInterval = 60

[Middleware.RateLimiter.Store.Redis]
Addr = ""
Username = ""
Password = ""
DB = 10

[Middleware.Casbin]
Disable = false
SkippedPathPrefixes = ["/api/v1/captcha/", "/api/v1/login", "/api/v1/current/", "/api/v1/crontab"]
LoadThread = 2
AutoLoadInterval = 3
ModelFile = "rbac_model.conf"
GenPolicyFile = "gen_rbac_policy.csv"
